# Generated by Django 5.0.3 on 2024-03-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0046_auto_20210921_2334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsetting",
            name="logo_img",
            field=models.ImageField(upload_to="media/app_logos/"),
        ),
    ]
